config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :contacts, only: [:new, :create]

  get 'welcome/index'
  root 'welcome#index'

  get '*path' => redirect('/')

end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,	:validate => true
	attribute :email,	:validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message,	:validate => true
	attribute :nickname,:captcha => true

	def headers
		{
			:subject => "Contact Form",
			:to => "ivanciitojf@gmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message'
			render :new
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 10)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params
		if @post.save
			redirect_to @post, notice: "Todo muy bien"
		else
			render 'new', notice: "Error no se puede crear"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @post.update post_params
			redirect_to @post, notice: "Actualizacion hecha"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private
	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end

	def find_post
		@post = Post.friendly.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(3).order("created_at desc")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygments < Redcarpet::Render::HTML
		def block_code(code, language)
			Pygments.highlight(code, lexer: language)
		end
	end
	def markdown(content)
		render = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_idented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true
		}
		Redcarpet::Markdown.new(render, options).render(content).html_safe
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Say Hello!</h1>

<div class="skinny_wrapper wrapper_padding">
	<h1>Thank you for you message...!</h1>
	<p>I'll get back to you son...!</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page_title">Say Hello!</h1>
	<div class="skinny_wrapper wrapper_padding">
		<%= form_for @contact do |f| %>
			<%= f.label :name %> <br>
			<%= f.text_field :name, required: true %>

			<br>

			<%= f.label :email %> <br>
			<%= f.email_field :email, required: true %>

			<br>

			<%= f.label :message %> <br>
			<%= f.text_area :message, as: :text %>

			<div class="hidden">
				<%= f.label :nickname %> <br>
				<%= f.text_field :nickname, hint: 'leave this field blank' %>
			</div>
			<%= f.submit 'Send Message', class: "button" %>
		<% end %>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>Ivan Jaramillo - Software Engineer</title>
	<link href='//fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
	<link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header id="main_navigation" class="clearfix">
		<%= link_to "Ivan Jaramillo", root_path, class: "name" %>
		<nav>
			<%= link_to "Blog", posts_path %>
			<%= link_to "Contact", new_contact_path %>
			<% if user_signed_in? %>
				<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
			<% end %>
		</nav>
	</header>
	<% if notice%>
		<p class="notice"><%= notice %></p>
	<% elsif alert %>
		<p class="alert"><%= alert %></p>
	<% end %>

	<%= yield %>

	<footer id="main_footer">
		<p class="copyright">&copy; 2015 Ivan Jaramillo</p>
		<nav>
			<a href="https://twitter.com/Ivanciito_JF" target="_blank"><i class="fa fa-twitter"></i></a>
			<a href="https://www.facebook.com/IvanciitoJF" target="_blank"><i class="fa fa-facebook"></i></i></a>
			<a href="https://instagram.com/ivanciito5/" target="_blank"><i class="fa fa-instagram"></i></a>
			<a href="https://es.foursquare.com/ivanciito_jf" target="_blank"><i class="fa fa-foursquare"></i></a>
			<a href="https://github.com/Ivan5" target="_blank"><i class="fa fa-github"></i></a>
			<a href="https://mx.linkedin.com/in/ivanjaramillof" target="_blank"><i class="fa fa-linkedin"></i></a>
			<a href="https://standardresume.co/IvanJaramillo" target="_blank"><i class="fa fa-dribbble"></i></a>

		</nav>
	</footer>

</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
 var disqus_shortname = 'ivanjaramillo';
 var disqus_identifier = '<%= @post.id %>';
 var disqus_title = '<%= @post.title %>';
 var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';
 
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//ivanjaramillo.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count, "error")%> prevented this posts from saving</h2>
		<ul>
			<% @posts.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>
	<%= f.label :title, "Titulo" %> <br>
	<%= f.text_field :title %> 

	<br>
	<br>

	<%= f.label :content, "Escribe tu Artículo" %> <br>
	<%= f.text_area :content %> 

	<br>
	<br>

	<%= f.submit %> 
<% end %>

app/views/posts/edit.html.erb
<h1 id="page_title">Edit Post</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page_title">Blog</h1>

	<div id="post_wrapper" class="skinny_wrapper">
		<% @posts.each do |post| %>
			<div class="post">
				<p class="date"><%= post.created_at.strftime('%b %d, %Y') %></p>
				<h2><a href=""><%= link_to post.title, post %></a></h2>
				<hr>
			</div>
		<% end %>
	</div>
	<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1 id="page_title">New Post</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @post.created_at.strftime('%A, %B %d')%></p>
		<h1><%= @post.title %></h1>
		<hr>
	</header>
	<div id="content">
		<%= markdown @post.content%>
	</div>

	<% if user_signed_in? %>
		<div id="admin_links">
			<%= link_to "Editar", edit_post_path(@post) %>
			<%= link_to "Eliminar", post_path(@post), method: :delete, data: {confirm: "Estas seguro?"} %>
		</div>
	<% end %>



	<hr>

	<div id="share_box">
		<p>Compartir <%= @post.title %></p>
		<a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title%> by @Ivanciito_JF - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
			<i class="fa fa-twitter"></i>
		</a>

		<a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
			<i class="fa fa-facebook"></i>
		</a>

		<a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
			<i class="fa fa-google-plus"></i>
		</a>
	</div>

	<hr>

	<%= render 'disqus' %>

</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearix">
		<div class="col-1 about homepage_content">
			<h2>About</h2>
			<hr>
			<p>Hello, I'm a software engineer living in México.</p><p> My expert area is web development also <a href="https://github.com/Ivan5" target="_blank">Front-end</a> and <a href="https://github.com/Ivan5" target="_blank">Back-end</a> and native Android development. </p>
			<p>
				<p><strong>Programming Languages</strong><p>
				- Java, JavaScript, Ruby, Python, PHP.
				<p><strong>Web Development</strong><p>
				- Ruby on Rails, Node.js, HTML5, CSS3, JavaScript..
			</p>
			
		</div>
		<div class="col-2 homepage_content">
			<%= image_tag "1.jpg" %>
		</div>
		<div class="col-3 homepage_content">
			<h2>Blog</h2>
			<hr>
			<% @posts.each do |post| %>
				<h3><a href=""><%= link_to post.title, post %></a></h3>
				<p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
			<% end %>
		</div>
</div>